### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by look4uz** [xwjim/DocRE-Rec#2]
When i run "gen_graph_data.py",there has an error at the line 95 , the console say that "TypeError: string indices must be integers"
How to deal with this error?
I try this program in windows and ubuntu , the question is same . Help!!!

**Comment by look4uz** [comment]
sry ,it is line 114

**Comment by xwjim** [comment]
Do you use the data of your own or DocRED?

**Comment by look4youi** [comment]
> Do you use the data of your own or DocRED
  I use the data in the TsinghuaCloud and the google driver  in the read.me

**Comment by look4uz** [comment]
> Do you use the data of your own or DocRED?

I use the data in the README.md  , I download it at the [TsinghuaCloud](https://cloud.tsinghua.edu.cn/d/99e1c0805eb64736af95/) or [GoogleDrive](https://drive.google.com/drive/folders/1Ri3LIILKKBi3aBJjUVCOBpGX5PpONHRK)

**Comment by xwjim** [comment]
Have you changed the code? Can you share your environment? I think the error occurs when there is a mistake in the data.

**Comment by look4uz** [comment]
> Have you changed the code? Can you share your environment? I think the error occurs when there is a mistake in the data.

I havn't change the code ,my env is pyhon 3.8 +torch 1.9.1+cu111
when i run the "gen_graph.py" there is no question ,it only in the "gen_graph_data.py"

**Comment by look4youi** [comment]
> Have you changed the code? Can you share your environment? I think the error occurs when there is a mistake in the data.
I havn't change the code ,my env is pyhon 3.8 +torch 1.9.1+cu111
when i run the "gen_graph.py" there is no question ,it only in the "gen_graph_data.py"

**Comment by xwjim** [comment]
Could you add print(item) before line 114 and tell me what print

**Comment by look4uz** [comment]
> Could you add print(item) before line 114 and tell me what print
it print "index"

**Comment by xwjim** [comment]
Sorry that I do not know what occurs? Do you run the command exactly as the instruction? Is the worker_num equal to 24?

**Comment by look4youi** [comment]
No  i use 
 # with Pool(processes=worker_num) as pthread:
    #     graph_data = pthread.map(cirle_reader, pbatch)
    for pdata in pbatch:
        graph_data = cirle_reader(pdata)

**Comment by look4youi** [comment]
i use 
    for pdata in pbatch[:1]:
        graph_data = cirle_reader(pdata)
replace
with Pool(processes=worker_num) as pthread:
graph_data = pthread.map(cirle_reader, pbatch)

**Comment by look4uz** [comment]
i use 
for pdata in pbatch:
    graph_data = cirle_reader(pdata)
replace 
with Pool(processes=worker_num) as pthread;
graph_data = pthread.map(cirle_reader, pbatch)

**Comment by xwjim** [comment]
If you do not want to use multiprocess. you can change as following, It may take a long time:

graph_data = []
 for pdata in pbatch:
        graph_data.append(cirle_reader(pdata))

**Comment by look4uz** [comment]
thnk you   i'll have a try
